### ISSUE TITLE
example errors 

### ISSUE THREAD

**Issue by andrewcz** [locuslab/convex_adversarial#6]
hi!
Hope your well!
just getting a few errors running the example -

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-e70fedd3458b> in <module>()
      1 import sys
      2 sys.path.append("../")
----> 3 from convex_adversarial import robust_loss_batch
      4 
      5 torch.manual_seed(1)

ImportError: cannot import name 'robust_loss_batch'

this is in the notebook example.
Best,
Andrew

**Comment by riceric22** [comment]
Hi Andrew,

Thanks for opening an issue, I actually forgot about this. A while back I changed the robust loss signature to use the batched form by default. I can update the example shortly, but a quick fix if you're such is to just change robust_loss_batch to robust_loss. 

~Eric

**Comment by fra31** [comment]
Hi!

I'm also running the example and I got this...

Traceback (most recent call last):
  File "lp_test.py", line 77, in <module>
    robust_ce, robust_err = robust_loss(robust_net, epsilon, Variable(X), Variable(y))
  File "/usr/local/lib/python3.5/dist-packages/convex_adversarial/dual.py", line 184, in robust_loss
    dual = DualNetBounds(net, X, epsilon, alpha_grad, scatter_grad)
  File "/usr/local/lib/python3.5/dist-packages/convex_adversarial/dual.py", line 107, in __init__
    subset_eye = Variable(X.data.new(self.I[-1].data.sum(), d.size(1)).zero_())
TypeError: new() received an invalid combination of arguments - got (Tensor, int), but expected one of:
 * (torch.device device)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (Tensor, int)
 * (torch.Storage storage)
 * (Tensor other)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (Tensor, int)

Do you know what this is due to?

Thanks a lot!
Francesco

**Comment by riceric22** [comment]
Hi Francesco,

This is because of the new features in pytorch 0.4 which returns 0 dimensional tensors instead of python numbers. Until I finish the port to 0.4 (I plan on finishing it towards the end of this month), you can use Pytorch 0.3.1 or 0.3.0 which should run without error.

**Comment by fra31** [comment]
Ok, many thanks!
